dbl-works/terraform

ecs/outputs.tf
This is to complete the data we need for ecsx config
=> Output nlb target arn

CHANGELOG.md, ecs/execution-role.tf
https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-denied-error-kms/﻿
=> allow ECS to generate data key (write to encrypted bucket)

CHANGELOG.md, README.md
will contain:
- s3-private: https://github.com/dbl-works/terraform/pull/51
- s3-public: https://github.com/dbl-works/terraform/pull/52
- RDS updates: https://github.com/dbl-works/terraform/pull/53
=> Prepare Next Release

s3-private/s3.tf
This also prevents accidently uploading public objects with an acl override.
=> Block all public access to private buckets

rds/README.md, rds/iam.tf
targeting via tags does not work﻿
=> Fix RDS View/List Permissions

CHANGELOG.md, s3-private/iam.tf, s3-private/outputs.tf
```terraform
resource "aws_iam_group_membership" "app-s3" {
name = aws_iam_user.app.name
group = module.s3-storage.group-usage-name
users = [
aws_iam_user.app.name
]
}
```
=> Expose S3 usage permissions via group

elasticache/README.md, elasticache/elasticache.tf, elasticache/outputs.tf, elasticache/variables.tf
combines:
https://github.com/dbl-works/terraform/pull/74
https://github.com/dbl-works/terraform/pull/75
https://github.com/dbl-works/terraform/pull/76
https://github.com/dbl-works/terraform/pull/77
in 1 branch so we can test all changes easily at once
=> All new features in one test branch

.github/workflows/ci.yml, .gitignore, stack/setup/app-secrets.json, stack/setup/terraform-secrets.json
stacked: https://github.com/dbl-works/terraform/pull/74
=> [chore] run CI on new stack module

iam/iam-policy-for-s3/README.md, iam/iam-policy-for-s3/main.tf, iam/iam-policy-for-s3/variables.tf, iam/iam-policy-for-s3/versions.tf, iam/iam-policy-for-taggable-resources/locals.tf, stack/setup/README.md, stack/setup/cloudflare.tf, stack/setup/main.tf, stack/setup/sample.env, stack/setup/variables.tf
=> [Fix] Stack module improvement

cloudflare/README.md, cloudflare/main.tf, cloudflare/variables.tf, stack/app/README.md, stack/app/cloudflare.tf
=> Fixes for bastion & Cloudflare API DNS record

.github/workflows/ci.yml, CHANGELOG.md, README.md, global-accelerator/README.md, global-accelerator/main.tf, global-accelerator/output.tf, global-accelerator/variables.tf, global-accelerator/versions.tf
```terraform
module "global-accelerator" {
source = "github.com/dbl-works/terraform//global-accelerator?ref=v2021.07.12"
project            = "my-project"
environment        = "production"
load_balancers = [
{
region   = "eu-central-1"
endpoint = "arn:aws:elasticloadbalancing:eu-central-1:${account_id}:loadbalancer/app/${project}-${environment}/xxx"
},
{
region   = "us-east-1"
endpoint = "arn:aws:elasticloadbalancing:us-east-1:${account_id}:loadbalancer/app/${ecs_name}/xxx"
}
]
health_check_path = "/livez"
health_check_port = 3000
client_affinity   = "SOURCE_IP"
}
```
Tested on a multi-region deployed application -> works ✅
=> new module: Global Accelerator

CHANGELOG.md, README.md, iam/README.md
document all changes from the current diff to the latest tag: https://github.com/dbl-works/terraform/compare/v2022.07.08...38915a9c5e59b9216f6b7675977acabd4e34572f
=> Prepare Release v2022.08.03

stack/app/README.md, stack/app/outputs.tf
We needs these for VPC peering
=> output NAT route tables from stack module

CHANGELOG.md, rds/README.md, rds/parameter-group.tf, rds/variables.tf
=> Add option to enable RDS replication

rds/parameter-group.tf
=> Fix logical_replication parameter name

CHANGELOG.md
State (main) was applied on Modifly staging and production.
=> Prepare release v2022.09.07

CHANGELOG.md, rds/rds.tf
Sets to follow the validation rules on DBName in terraform/aws
To fix this error
```
Error: creating RDS DB Instance (ab-cde-fgh): InvalidParameterValue: DBName must begin with a letter and contain only alphanumeric characters.
```
Apply a config with a project name with dashes and see whether you can make an RDS DB without and with this change.
git revert
=> Replace non-alphanumeric chars with underscore

cloudwatch-snowflake/README.md
=> cloudwatch-snowflake: Update README.md in cloudwatch snowflake module

cloudwatch-snowflake/README.md, cloudwatch-snowflake/main.tf, cloudwatch-snowflake/outputs.tf
Update lambda function name and add lambda arn in the outputs so it can be reused
=> cloudwatch-snowflake: Update lambda function name

cloudwatch-snowflake/outputs.tf
=> Fix Inconsistent Return Type for Cloudwatch Snowflake Output

snowflake/cloud/deploy-user.sql, snowflake/cloud/readonly-user.sql
Adds a SQL script to create a readonly role/user on Snowflake to be used e.g. in Tableau/Metabase/Grafana
=> Adds SQL Script For A Readonly User/Role

autoscaling/ecs/README.md, autoscaling/ecs/alarms.tf, autoscaling/ecs/variables.tf, ecs/README.md, ecs/autoscaling.tf, ecs/variables.tf, stack/app/README.md, stack/app/ecs.tf, stack/app/variables.tf
=> Trigger scale down when no data points available

iam/iam-policy-for-ecs/core/README.md, iam/iam-policy-for-ecs/core/main.tf, iam/iam-policy-for-ecs/core/variables.tf, iam/iam-policy-for-s3/README.md, iam/iam-policy-for-s3/main.tf, iam/iam-policy-for-s3/variables.tf, s3-private/README.md, s3-private/iam.tf, s3-private/variables.tf
=> Enable that we can (dis)allow listing all ECS Clusters or S3 Buckets

ecs/execution-role.tf, s3-private/iam.tf
Co-Authored-By: Grigory Moroz <moroz.grigory@gmail.com>
=> Adds missing permissions to retrieve object versions from S3

ecs/log-group.tf, s3-private/README.md, s3-private/iam.tf, s3-private/s3.tf, s3-private/variables.tf
@marcqualie, mind if we backstream these improvements? Thanks 🙂 🚀 
I'm particularly eyeing the ECS log group bug and short retention period.
=> Backstream updates from @cogsworth4 fork

.github/pull_request_template.md
=> [Chore] Add pull request template

CHANGELOG.md, stack/app/nat.tf, stack/app/outputs.tf, stack/app/variables.tf, stack/app/vpc-peering.tf
Make NAT optional in stack/app modules
Cut down AWS costs
=> [Chore] Make NAT optional in stack/app modules

nat/nat.tf, stack/app/README.md, stack/app/nat.tf, stack/app/outputs.tf, stack/app/vpc-peering.tf, stack/setup/README.md, stack/setup/variables.tf
=> Default Stack Module to Zero EIPs

CHANGELOG.md, ecr/README.md, ecr/ecr.tf, ecr/variables.tf, stack/core/ecr.tf, stack/core/variables.tf
Add lifecycle policy so ECR images will be expired after some requirements are fulfilled
Cut down AWS costs
=> [Chore] ecr: Add lifecycle policy

CHANGELOG.md, stack/app/README.md, stack/app/ecs.tf, stack/app/elasticache.tf, stack/app/outputs.tf, stack/app/variables.tf, stack/setup/outputs.tf
stack/app: Skip elasticache in stack/app stack
stack/setup: Add certificate arn in the output
=> Add certificate arn in stack setup output

ecs/log-group.tf, ecs/variables.tf, stack/app/README.md, stack/app/ecs.tf, stack/app/rds.tf, stack/app/variables.tf
Minor improvement - Add output and variables
=> [Chore] Minor improvement - Add output and variables

CHANGELOG.md, stack/app/README.md, stack/app/elasticache.tf, stack/app/variables.tf
=> stack/app: Add elasticache_name as variables

.github/workflows/ci.yml, CHANGELOG.md, rds/rds.tf, rds/variables.tf, slack/sentry/README.md, slack/sentry/main.tf, slack/sentry/variables.tf, slack/sentry/versions.tf, stack/app/rds.tf, stack/app/variables.tf
Introduce new module slack/sentry 
Automate the process for sending slack notification when there is sentry issue alert
=> slack/sentry: Slack notifier for Sentry issue alert

.github/workflows/ci.yml, CHANGELOG.md, ecs_service/README.md, ecs_service/ecs_service.tf, ecs_service/ecs_task_definition.tf, ecs_service/task-definitions/web.json, ecs_service/task-definitions/web_with_logger.json, ecs_service/variables.tf, ecs_service/versions.tf, iam/iam-for-deploy-bot/main.tf
=> ecs_service: Add new module

CHANGELOG.md, stack/app/README.md, stack/app/ecs.tf, stack/app/variables.tf
=> stack/app: Update README.md

ecs_service/README.md, ecs_service/ecs_service.tf, ecs_service/task-definitions/sidekiq_with_logger.json
=> Chore sidekiq task definition

CHANGELOG.md, global-accelerator/README.md, global-accelerator/main.tf, global-accelerator/variables.tf
=> global-accelerator: add weight to load_balancers variable

stack/setup/README.md, stack/setup/main.tf, stack/setup/variables.tf
Fixes a bug with a replica in a different region but on the same domaiin
=> Allow creating a certificate for replicas in different regions

rds/iam.tf, rds/variables.tf
Following the db user naming convention, we would not include region in the read only and admin user name
Allow user to connect to db successfully
=> [Chore] Fix db user name

aws-transfer/outputs.tf, cloudwatch-kinesis/README.md, cloudwatch-kinesis/cloudwatch-subscription-filter.tf, cloudwatch-kinesis/firehose-delivery-stream.tf, cloudwatch-kinesis/locals.tf, cloudwatch-kinesis/variables.tf, cloudwatch-kinesis/versions.tf, ecs-deploy/ecs_task_definition.tf, ecs-deploy/locals.tf, ecs-deploy/task-definitions/web.json, ecs-deploy/variables.tf, ecs/execution-role.tf, s3-private/outputs.tf, s3-private/s3.tf
* actually, log volume should be optional --> choose it for MVPs due to its simplicity (but don't use it at scale)
* kinesis as alternative to the log volume attached to the web task for apps at scale
also see https://github.com/dbl-works/terraform/pull/205
closes https://github.com/dbl-works/terraform/pull/205
=> Logging at scale

cloudwatch-kinesis/README.md, cloudwatch-kinesis/firehose-delivery-stream.tf, cloudwatch-kinesis/locals.tf, cloudwatch-kinesis/variables.tf, lambda/iam.tf, lambda/output.tf, lambda/variables.tf
Improve lambda and cloudwatch-kinesis
=> lambda, cloudwatch-kinesis: Improvement

CHANGELOG.md, cloudwatch-kinesis/cloudwatch-subscription-filter.tf, cloudwatch-kinesis/firehose-delivery-stream.tf, cloudwatch-kinesis/variables.tf
- Add regional variable to allow deployment for regional service
- Add subscription_filter_pattern as variable
=> cloudwatch-kinesis: add regional to allow deployment for regional service

CHANGELOG.md, rds/rds.tf, rds/variables.tf, s3-public/s3.tf, stack/app/rds.tf, stack/app/variables.tf
- Add identifier as variable
- Add public bucket configuration to avoid ACCESS DENIED error. (https://github.com/hashicorp/terraform-provider-aws/issues/31021)
=> s3-public: fix public bucket access ACL

CHANGELOG.md, ecs-deploy/variables.tf, ecs-task/README.md, ecs-task/locals.tf, ecs-task/main.tf, ecs-task/task-definitions/main.json, ecs-task/variables.tf
Create task definition for ECS service task
Enable user to run release command like bundle exec rails db:create and etc
=> ecs-task: run release task in container

CHANGELOG.md, fivetran/connectors/lambda/README.md, fivetran/connectors/lambda/fivetran.tf, fivetran/connectors/lambda/main.tf, fivetran/connectors/lambda/variables.tf
=> fivetran/connectors/lambda: add lambda_name

ecs/README.md, ecs/alb.tf, ecs/nlb.tf, ecs/variables.tf
- make keep alive timeout configurable
- NLB also respects configured timeout
=> Make Keep Alive Configurable

CHANGELOG.md, stack/app/ecs.tf, stack/app/variables.tf
https://github.com/dbl-works/terraform/pull/232#pullrequestreview-1544822338
=> pass keep_alive_timeout through to stack module

CHANGELOG.md, elasticache/elasticache.tf, stack/app/README.md, stack/app/elasticache.tf, stack/app/variables.tf
=> Patch 'transit_encryption_enabled' through to stack module

.github/workflows/ci.yml, CHANGELOG.md, http-proxy/README.md, http-proxy/eip.tf, http-proxy/instance.tf, http-proxy/key-pair.tf, http-proxy/security-groups.tf, http-proxy/variables.tf, http-proxy/versions.tf
- New Module 'HTTP Proxy' to assume a static IP
- fix readme
- update changelog
A cheap and simple way to assume a static IP that does not need to scale at the level of a NAT.
=> New Module: HTTP Proxy to assume a static IP

.github/workflows/ci.yml, CHANGELOG.md, lambda/iam.tf, lambda/main.tf, lambda/variables.tf
Add lambda role name to lambda module
- We can skip the creation of role in the module
=> lambda: add lambda_role_name

CHANGELOG.md, ecs/outputs.tf, ecs/service-discovery.tf, ecs/variables.tf, stack/app/ecs.tf, stack/app/outputs.tf, stack/app/variables.tf
Add service_discovery_enabled to ecs and stack/app module to enable the service discovery features
Enable service discovery
=> ecs: add service_discovery_enabled variables

http-proxy/README.md, http-proxy/security-groups.tf, http-proxy/tinyproxy.conf, http-proxy/variables.tf
* improve security by limiting egress traffic to what is required instead of all of the internet
* add documentation on how to configure Tinyproxy
=> Secure Proxy by limiting egress traffic & improve its documentation

ecs/outputs.tf
=> Fix: ECS output when service discovery is disabled

CHANGELOG.md, http-proxy/README.md, http-proxy/security-groups.tf, http-proxy/variables.tf
Makes it easier to understand the module and allows installing updates when maintenance mode is enabled.
=> Improve Proxy Module

CHANGELOG.md, ecs/README.md, ecs/target-groups.tf, ecs/variables.tf, stack/app/ecs.tf, stack/app/variables.tf
Add health_check_options as variables
We can configure the health check options easily
=> ecs: add health_check_options as variables

http-proxy/README.md, http-proxy/instance.tf, http-proxy/security-groups.tf, http-proxy/variables.tf
adds better descriptions and fixes the readme
=> Proxy Improvements

CHANGELOG.md, stack/setup/cloudflare.tf
Prevent clickjacking
https://en.wikipedia.org/wiki/Clickjacking
=> stack/setup: prevent clickjacking

CHANGELOG.md, cloudflare/cloudflare-ruleset.tf, stack/setup/cloudflare.tf
=> cloudflare: prevent clickjacking

github-backup/src/main.rb
Implement pagination for the GitHub API, which by default returns 30 repos (and 100 at max).
=> implement pagination

github-backup/src/main.rb
=> minor clean up

CHANGELOG.md, script/database-roles/main.tf
=> script/database-roles: Retrieve DB username from secret manager

.github/workflows/ci.yml, CHANGELOG.md, cloudwatch-kinesis/firehose-delivery-stream.tf, cloudwatch-kinesis/variables.tf, cloudwatch-kinesis/versions.tf, stack/setup/main.tf
hashicorp/aws version: upgrade to v5 
Allow the usage of ruby 3 in the lambda function
=> hashicorp/aws version: upgrade to v5

CHANGELOG.md, rds/variables.tf, stack/app/variables.tf
Update rds ca_cert_identifier to rds-ca-ecc384-g1
=> rds: update ca_cert_identifier

CHANGELOG.md, ecs-deploy/cluster/services.tf, ecs-deploy/cluster/variables.tf
Add regional to the ecs-deploy/cluster module
=> ecs-deploy/cluster: add regional variables

ecs-deploy/cluster/README.md
for convenience, the AWS docs on this are hard to find.
=> document cpu/memory options for ECS Fargate

rds/subnet-group.tf
Create DB subnet group before destroy
closes https://github.com/dbl-works/terraform/issues/267
=> [chore] create db subnet group before destroy

CHANGELOG.md, ecs/ecs-cluster.tf, ecs/variables.tf, slack/sentry/versions.tf, stack/app/ecs.tf, stack/app/variables.tf
Allow the user to disable containerInsights
Reduce cost on Cloudwatch
=> ecs: add enable_container_insights

http-proxy/README.md
Document how to use the HTTP Proxy in a Ruby/Rack-based app.
Makes it easier to setup.
=> Better docs for HTTP Proxy

CHANGELOG.md, ecs-deploy/cluster/services.tf, ecs-deploy/cluster/variables.tf, ecs-deploy/service/ecs_service.tf, ecs-deploy/service/variables.tf
Allow the configuration of vpc_name
=> ecs-deploy: add vpc_name to variables

lambda/variables.tf
Upgrade Lambda default runtime from nodejs 16 to 20
http://go/dbl/74
=> Upgrade Lambda default runtime from nodejs 16 to 20

ecs-deploy/cluster/services.tf, ecs-deploy/cluster/variables.tf
=> ecs-deploy/cluster: add cluster_name variables

.github/workflows/ci.yml, azure/blob-storage/README.md, azure/blob-storage/main.tf, azure/blob-storage/variables.tf, azure/blob-storage/versions.tf
=> azure/blob-storage: new module

.github/workflows/ci.yml, azure/container-registry/README.md, azure/container-registry/main.tf, azure/container-registry/variables.tf, azure/container-registry/versions.tf
=> azure/container-registry: new module

.github/workflows/ci.yml, azure/container-app/README.md, azure/container-app/main.tf, azure/container-app/variables.tf, azure/container-app/versions.tf
=> azure/container-app: new module

.github/workflows/ci.yml, azure/database/postgres/README.md, azure/database/postgres/main.tf, azure/database/postgres/network.tf, azure/database/postgres/output.tf, azure/database/postgres/variables.tf
=> azure/database/postgres: new module

.github/workflows/ci.yml
As ridiculous as it may sound, between some statements, a new line breaks the CI without any error or validation warning.
=> fix: CI not running

azure/database/postgres/parameters.tf, azure/database/postgres/variables.tf, azure/stack/app/variables.tf
=> azure/database: Add server parameters support

azure/container-app/main.tf, azure/container-app/variables.tf, azure/stack/app/container-app.tf, azure/stack/app/container-registry.tf, azure/stack/app/observability.tf, azure/stack/app/variables.tf
=> azure/container-app: allow multiple containers

azure/container-app/main.tf, azure/container-app/variables.tf, azure/stack/app/variables.tf
=> azure/stack/app: add variables for container app

aws/stack/app/variables.tf
=> aws/stack/app: add host_header in the var

aws/ecs/alb.tf, aws/ecs/variables.tf, aws/stack/app/ecs.tf, aws/stack/app/s3-private.tf, aws/stack/app/variables.tf
=> aws/ecs: add no_of_subnets_in_alb, sse_algorithm

aws/s3-private/replication.tf, aws/s3-private/variables.tf, aws/s3-public/replication.tf, aws/stack/app/README.md, aws/stack/app/variables.tf
=> aws/s3: limit replication role name characters

aws/secrets/secrets.tf, aws/stack/setup/main.tf, aws/stack/setup/outputs.tf
Prevent KMS key being created twice
=> aws/stack/setup: fix duplication kms key

aws/autoscaling/ecs/main.tf, aws/autoscaling/ecs/variables.tf, aws/rds/parameter-group.tf, aws/s3-private/replication.tf
Terraform very often trigger changes even if there is no changes.
This PR should remove those ghost changes
=> aws/autoscaling/ecs: prevent ghost change

aws/cloudtrail/log-ingestor/s3.tf, aws/stack/global/s3-private.tf, aws/stack/global/variables.tf
=> aws/s3-private: add sse_algorithm options

.vscode/settings.json, aws/ecs/README.md, aws/ecs/alb.tf, aws/ecs/variables.tf, aws/s3-private/s3.tf, aws/s3-private/variables.tf, aws/s3/main.tf, aws/s3/variables.tf, aws/stack/app/ecs.tf, aws/stack/app/variables.tf, aws/waf/README.md, aws/waf/outputs.tf, aws/waf/variables.tf, aws/waf/versions.tf, aws/waf/waf.tf
=> feat: extract WAF into its own module

aws/slack/chatbot/README.md, aws/slack/chatbot/main.tf
awscc is keep throwing error and causing problem for terraform apply
=> aws/slack/chatbot: fix awscc error

aws/cloudwatch/README.md, aws/cloudwatch/alarm.tf, aws/cloudwatch/variables.tf, aws/ecs/README.md, aws/stack/app/ecs.tf
Add alarm for running task count
=> aws/cloudwatch: alarm for running task count

azure/stack/setup/key-vault.tf
=> azure: add key vault permission to principal id

aws/elasticache/elasticache.tf, aws/elasticache/variables.tf
This new option is now required for Elasticache.
=> chore: update Elasticache to support "transit_encryption_mode" option

aws/rds/README.md
Added a checklist on how to upgrade RDS to the next major version.
=> Introduce Engine Upgrade Checklist

aws/ecs-deploy/cluster/README.md
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-tasks-services.html#fargate-tasks-size
=> Update AWS ECS Task container sizes

aws/rds/rds.tf, aws/rds/variables.tf
- Expose the variable `storage_type` in the `rds` module
We want to change our rds `storage_type` to `gp3` and we need the variable to be exposed
=> Expose variable `storage_type` in RDS module

aws/aurora/main.tf, aws/aurora/variables.tf, aws/stack/app/aurora.tf, aws/stack/app/variables.tf
=> feat(aws-aurora): allow custom subnet group & setting min-capacity
