dbl-works/terraform

s3-private/s3.tf

We need this in order to upload files directly to S3 from our frontends.
Since we use multi tenant setups, we cannot give a list of allowed origins upfront.
A presigned url is required to upload, so the security risk of allowed origins is non existent.

Add CORS headers for private s3 buckets

---

ecs/outputs.tf

We need to be able to attach add﻿ multiple  certificates to  an ALB, see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_certificate
Unsure why tests for the S3 modules are failing. Code is untouched and locally, they are passing. (I guess, the lastest version is installed, which might have breaking changes ...)

Output HTTPS ALB ARN for ECS

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
kms-key/kms-aliases.tf
s3-private/s3.tf
s3-public/s3.tf

Lot of syntax in the S3 library is deprecated. (Check [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket))
Replace the deprecated syntax to ensure smoother transition to the latest version
closes #70
closes #69

[Chore] Replace S3 deprecated syntax

---

ecs/cloudwatch.tf
ecs/ecs-cluster.tf
ecs/execution-role.tf
ecs/iam.tf
ecs/nlb.tf
ecs/security-groups.tf
ecs/target-groups.tf

Some resource get recreated due to the description changing, but this is safe.
This is mainly to prepare for fully regional clusters and custom name overrides.

ECS: Use local.name consistently

---

ecs/execution-role.tf
ecs/locals.tf
ecs/variables.tf

Fully backwards compatible without any changes. Default name is `${var.project}-${var.environment}`

ECS: Custom cluster name

---

vpn/README.md
vpn/instance.tf
vpn/variables.tf
vpn/vpc.tf

- allow passing AZ's since only 1 AZ is needed for the creation of VPN

[Chore] Pass only 1 availability_zone to the VPN module 

---

ecs/security-groups.tf
rds/README.md
rds/rds.tf
rds/variables.tf
stack/app/README.md
stack/app/ecs.tf
stack/app/outputs.tf
stack/app/variables.tf
stack/app/vpc-peering.tf

* Allow launching stack with VPC peering without RDS read-replica
* "bug" fix: if passed duplicated IP (ranges) for the ecs-ssh ingress policy, we get a hard error. We now ensure, this is a unique list

Allow launching stack with VPC peering without RDS read-replica

---

elasticache/README.md
elasticache/security-group.tf
elasticache/variables.tf
stack/app/README.md
stack/app/elasticache.tf
stack/app/variables.tf

Optionally allow that we can access a Redis cluster in another VPC/region.
Tested on the test application ✅

Allow passing multiple CIDR blocks to Elasticache Security Group Rule

---

rds/parameter-group.tf
rds/rds.tf
rds/variables.tf

This will allow upgrade from `13` -> `14`. We can't delete a parameter group or modify it's "family" while it is associated with an instance.
The idea here is we would always support exactly 2 versions of pg with our latest module.
Once 15 is accepted and stable, we would remove `13` from the module and have `14`/`15`

Add postgres14 parameter group

---

elasticache/elasticache.tf
elasticache/variables.tf

Smaller/test projects don't need the failover. Requires a minimum of 2 nodes to be active which doubles the cost.

Elasticache: Allow opt-out of automatic failover

---

CHANGELOG.md
elasticache/README.md
elasticache/elasticache.tf
elasticache/variables.tf

Allow user to pass in `maxmemory_policy` to elasticache. If it is not passed, default value will be set as `volatile-lru`.

[SC 2864] Add maxmemory_policy to elasticache

---

stack/app/ecs.tf

Cloudwatch metrics for stacks outside `eu-central-1` are not working when using the stack module.
```terraform
Terraform will perform the following actions:
~ resource "aws_cloudwatch_dashboard" "main" {
~ dashboard_body = jsonencode(
~ {
~ widgets = [
~ {
~ properties = {
~ region  = "eu-central-1" -> "us-east-1"
}
},
~ {
~ properties = {
~ metrics              = [
- [
- {
- expression = "100*(m1/m2)"
- id         = "e1"
- label      = "MemoryUsage"
- region     = "eu-central-1"
- yAxis      = "left"
},
],
+ [
+ {
+ expression = "100*(m1/m2)"
+ id         = "e1"
+ label      = "MemoryUsage"
+ region     = "us-east-1"
+ yAxis      = "left"
},
],
[
"ECS/ContainerInsights",
"MemoryUtilized",
"ServiceName",
"web",
"ClusterName",
"${project}-production-us-east",
{
id      = "m1"
visible = …
```

Stack: Pass "region" to ECS module (fixes CloudWatch Dashboard)

---

stack/app/versions.tf

To get rid of the error below:
```
│ Warning: Provider aws.peer is undefined
│ 
│   on main.tf line 6, in module "stack":
│    6:     aws.peer = aws.peer
│ 
│ Module module.stack does not declare a provider named aws.peer.
│ If you wish to specify a provider configuration for the module, add an entry for aws.peer in the required_providers block within the module.
```

stack: Declare aws.peer in stack module

---

CHANGELOG.md
rds/parameter-group.tf

Set parameter to default as is also recommended by Fivetran.

Set RDS parameter wal_buffers to default

---

CHANGELOG.md
certificate/README.md
elasticache/variables.tf
stack/app/elasticache.tf
stack/app/variables.tf

it
1. Moves elasticate cluster_mode & maxmemory_policy values into variables in order to allow non-cluster mode Redis setup
2. Increases elasticache node_count to 2 as required for default failover mode.
https://app.shortcut.com/lih/story/30676/move-lufthansa-flightpass-lhfp-staging-from-heroku-to-aws-ecs-cw37
try to setup
or you can to [this branch](https://github.com/lh-innovationhub/lufthansa-flightpass/pull/882) and see `terraform state list` results
git revert

Move app cluster mode value into a variable

---

cloudwatch-snowflake/README.md
cloudwatch-snowflake/main.tf
cloudwatch-snowflake/tracker/index.js
cloudwatch-snowflake/tracker/utils/cloudwatch.js
cloudwatch-snowflake/variables.tf

In case we need to deploy different lambdas across multiple regions, this change allows us to do so
Also, if the stats is `Maximum` or `p99.9` the current regex to clean the Query Id name was insuffcient.

allow passing path to custom lambda & improve query id regex

---

autoscaling/ecs/README.md
autoscaling/ecs/alarms.tf
autoscaling/ecs/variables.tf
ecs/variables.tf
stack/app/variables.tf

Support target response time as ECS autoscaling metrics
ECS can be scaled up based on the target response time and therefore enhance the user experience time

autoscaling/ecs: Support target response time as ECS autoscaling metrics

---

cloudflare/README.md
cloudflare/main.tf
cloudflare/tls.tf
cloudflare/variables.tf
elasticache/outputs.tf
stack/README.md
stack/app/README.md
stack/app/cloudflare.tf
stack/app/elasticache.tf
stack/app/outputs.tf
stack/app/sample.env
stack/app/variables.tf
stack/setup/README.md
stack/setup/cloudflare.tf
stack/setup/sample.env

- cloudflare: 
- Allow users to declare the `s3_cloudflare_records` instead of hardcording it to [cdn, app] 
- Allow user to declare the worker script name
- elasticache:
- fix cluster mode elasticache endpoint output
- stack/app:
- Add `alb_dns_name` as output
- Make `db_instance_class_memory_in_gb` as optional variables
- stack/app
- Add cloudflare TLS setup

chore: Refactoring 

---

CHANGELOG.md
ecs/README.md
ecs/execution-role.tf
ecs/variables.tf

Some simple apps might not need any secrets, thus this allows to launch an ECS Cluster without passing secret ARN(s) and KMS key ARN(s)
I'm toying with an app that does not need secrets, and I don't want to launch resources that won't be needed.

Allow Creating an ECS Cluster without Secrets/KMS Keys

---

cloudwatch/main.tf

Add p99 and average to CPU and Memory metrics graph

cloudwatch: Add p99 and average to CPU and Memory metrics graph

---

certificate/outputs.tf
ecs/README.md
ecs/alb.tf
ecs/variables.tf
stack/app/README.md
stack/app/ecs.tf
stack/app/variables.tf

- Adds Basic SNI Support
- also allow stack to pass additional certificates through
https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_certificate
Given a multi-region application, I want to add certificates for
* api.my-app.test
* api.eu-central-1.my-app.test
* api.us-east-1.my-app.test
to test a specific region directly. This is not doable with wildcard certificates due to the usage third level domains.
Tested here:
https://go/terraform-151-1 # api.my-app.test/healthz
https://go/terraform-151-2 # api.eu-central-1.my-app.test/healthz
https://go/terraform-151-3 # api.us-east-1.my-app.test/healthz
**before**

Support multiple SSL Certificates per ALB (SNI)

---

CHANGELOG.md
rds/iam.tf
rds/parameter-group.tf
rds/rds.tf
rds/security-group.tf
rds/subnet-group.tf
rds/variables.tf

When adding a 2nd DB to the same environment/project, this currently would fail:
> Error: creating Security Group (dbl-production-db): InvalidGroup.Duplicate: The security group 'dbl-production-db' already exists for VPC 'vpc-09ba3920de77c22f8'
>
> Error: creating DB Parameter Group: DBParameterGroupAlreadyExists: Parameter group dbl-production-postgres13 already exists
>
> Error: creating DB Parameter Group: DBParameterGroupAlreadyExists: Parameter group dbl-production-postgres14 already exists
>
> Error: creating RDS DB Subnet Group (dbl-production): DBSubnetGroupAlreadyExists: The DB subnet group 'dbl-production' already exists.
In the test that resulted in above errors, a `name` was explicitly passed (`"${local.project}-${local.environment}-datascience"`)

RDS: Use custom name everywhere if passed

---

rds/rds.tf

https://github.com/dbl-works/terraform/blob/main/rds/rds.tf#L14
If we were to specify a minor version, e.g., 14.5 then var.engine_version == "14" would evaluate to "false", and use the v13 parameter group, which then results in an error.
To the user, it is not obvious, that a minor version cannot be specified, especially since passing a minor version is generally supported by RDS.
resolves https://github.com/dbl-works/terraform/issues/153

[Chore] Support patch version in RDS module

---

iam/iam-policy-for-taggable-resources/project-developers-policies.tf

This is to include some of the read access command for ec2 container (reference policy: AmazonEC2ContainerRegistryReadOnly)

[Chore] Add batch command for ecs

---

ecs/log-group.tf

var.name may be null, if so, local.name sets a default

Fix: Loggroup name: use local name

---

CHANGELOG.md
stack/app/README.md
stack/app/ecs.tf
stack/app/variables.tf
stack/setup/cloudflare.tf
stack/setup/main.tf
stack/setup/outputs.tf

- Add certificate_arn as optional variables. Allows the user to decide which aws acm certificate to be used.
- Always use the most recent aws_acm_certificate to avoid the multiple certificates error.
- Remove the creation of aws_acm_certificate when is_read_replica_on_same_domain is true.
- Pass cloudflare_validation_hostnames as output.

[Chore] Improve the usage of aws_acm_certificates in stack/app and stack/setup

---

CHANGELOG.md
ecr/README.md
ecr/ecr.tf
ecr/variables.tf

Add ECR lifecycle policy rules to keep at least 1 images on important branch
When running certain tasks (spin up a task on ECS), we require the image to exist on ECR

[Chore] Add ECR lifecycle policy rules to keep at least 1 images on important branch

---

stack/app/outputs.tf

fixes in stack / main / output
```
│ Error: Inconsistent conditional result types
│ 
│   on .terraform/modules/stack/stack/app/outputs.tf line 10, in output "redis_url":
│   10:   value = var.skip_elasticache ? "" : module.elasticache[0].endpoint
│     ├────────────────
│     │ module.elasticache[0].endpoint is list of string with 1 element
│     │ var.skip_elasticache is false
│ 
│ The true and false result expressions must have consistent types. The 'true' value is string, but the 'false' value is list of string.
```
which slipped through review here https://github.com/dbl-works/terraform/pull/174/

FIX: Elasticache output is a list

---

stack/app/ecs.tf

In ecs/execution-role.tf, tf only loop the variables and make sure the bucket/* is accessible. We should not pass the variables in the `bucket/*` format => it will result in `bucket/*/*` in the policy

[Hotfix] Fix S3 bucket access in ecs module

---

nat/nat.tf
nat/variables.tf
rds/parameter-group.tf
rds/rds.tf
rds/security-group.tf
rds/subnet-group.tf
rds/variables.tf
stack/app/README.md
stack/app/rds.tf
stack/app/variables.tf
stack/app/vpc-peering.tf
vpc/outputs.tf

Fix VPC peering when deploying the application task in ECS to a public subnet instead of a private subnet.
This requires adding a route for the peering-connection to the route-table associated with the public subnets (so far this route was only added to the tables associated with the private subnets).
We want to save costs for some stacks and not have a NAT. One solution is to move the application tasks to a public subnet (and secure them via policies).

Vpc peering public subnets

---

ecs_service/ecs_service.tf
ecs_service/variables.tf

- WIP: allow passing regional names for ecs clusters
- fix: add cluster_name var
- iam role, target groups, security groups are regional

Consider ECS Clusters with regional name

---

ecs_service/README.md
ecs_service/locals.tf
ecs_service/task-definitions/logger.json
ecs_service/variables.tf

Allow granting access to secrets to the logger container
I want to move API keys for external log sinks out of the vector config file (git tracked) to AWS Secrets Manager.
Example from a vector config file:
```toml
[sinks.logtail_http_sink.auth]
strategy = "bearer"
token    = "${LOGTAIL_VECTOR_SINK_TOKEN}"
```
For this to work, we need to grant the logger container access to some (but not all) secrets.
We should use a different `secrets` variable for this, since the logger should not have access to all secrets; it is not necessary and can only lead to bugs where we inject sensitive data into the logs by accident.

Allow logger side-cear container to access secrets

---

CHANGELOG.md
iam/iam-for-humans/human-policies.tf

In the latest AWS, user is allowed to name the MFA service.
Therefore the mfa service is no longer a static value (eg. aws:username)
The current setup only allow user to name the MFA service using the aws username
```
{
"Sid": "AllowManageOwnVirtualMFADevice",
"Effect": "Allow",
"Action": [
"iam:CreateVirtualMFADevice",
"iam:DeleteVirtualMFADevice"
],
"Resource": "arn:aws:iam::*:mfa/$${aws:username}"
}
```
This update
- allow the user to create MFA under any name
- ~deny users from performing most of the actions unless they setup their MFA~ (Remove this because it prohibits a lot of cli actions)
~_eg. User would see only the loading spinner when trying to access the ECS cluster_~
https://github.com/dbl-works/terraform/issues/163

[Chore] Update MFA policy

---

iam/iam-for-humans/human-policies.tf

Creating the module can fail on first execution, and the second execution will then succceed. This is because dependencies are not declared correctly.
Modules should not randomly fail.

Fix Dependencies on Humans Group/Policies

---

cloudwatch/main.tf

the stats label is "... per min", but if the time range of the dashboard is changed to e.g. 1 week, cloudwatch by default auto-adjusts the period (e.g. to 1 hour), but the label still prints " ... per min", which is very confusing.
This PR fixes this by forcing the dashboard to always respect the configured period regardless of the time range chosen.

Fix period override in CloudWatch

---

CHANGELOG.md
rds/README.md
rds/parameter-group.tf
rds/rds.tf
rds/variables.tf

Previously, if the engine version was not 14, version 13 was assumed for the parameter group.
This obviously does not allow creating new instances using any other version.
Postgres 15 was released on AWS.

Ensure the correct parameter group is used, regardless of engine version

---

CHANGELOG.md
ecs-deploy/README.md
ecs-deploy/ecs_service.tf
ecs-deploy/variables.tf
ecs/README.md
ecs/alb.tf
ecs/security-groups.tf
ecs/variables.tf
stack/app/README.md
stack/app/ecs.tf
stack/app/variables.tf

- ecs-deploy: add aws_lb_target_group_arn and allow configuration of load_balancer block
- ecs, stack/app: add alb_listener_rule and allow_alb_traffic_to_ports options

ecs: add alb listener rule

---

stack/app/README.md
stack/app/ecs.tf
stack/app/outputs.tf
stack/app/rds.tf
stack/app/variables.tf

Allow launching a `stack` module without a database
We want a replication stack to move compute resources closer to clients, but due to data privacy issues in that geo region, we do not want to have a copy of the database in that geo region.
Has been tested ✅ 
⚠️ on update, you will need to move the terraform state of an existing database, since the pointer changed from something like `module.stack.module.rds.arn` to `module.stack.module.rds[0].arn`.

Allow creating a stack module without database

---

CHANGELOG.md
ecs-deploy/ecs_service.tf

Ignore desired_count after the aws_ecs_service creation.
Terraform apply should not affect the current number of task count triggered by autoscaling

ecs-deploy: ignore desired_count after the aws_ecs_service creation

---

s3-private/s3.tf

Fixes The bucket does not allow ACLs
Which is broken due to updates from AWS to how S3 works.
tested: create a new private bucket with default settings -> works ✅

[FIX] S3 Private: The bucket does not allow ACLs

---

rds/parameter-group.tf

- only log DDL not everything on the DB
- set log retention to 3 days
Prior to this PR, RDS would log every statement, including select statements.
This can lead to serious amounts of logs collected during traffic spikes.
In one app, this caused 390 GiB of logs to be produced within 24 hours.
Increasing storage beyond 400 GiB is not a fast solution: https://repost.aws/knowledge-center/rds-stuck-modifying

RDS: less logging

---

CHANGELOG.md
rds/parameter-group.tf

Set log_statement to none since logs are seldom to be used for debugging purpose and it will also expose the password upon creation of role/user
Reduce the storage consumption in RDS

[Chore] Set log statement to none

---

ecs/README.md
ecs/alb.tf

The current setting of 10 minutes is too long. The default is 60, which we should keep.
Rails /w Puma apps even default to 20 seconds. If you were to use a Ruby/Puma server with its default settings, having the LB keep connections open for more than 20 seconds 
will lead to bugs.
Also see https://github.com/puma/puma/issues/957
The update can be done in-place

Set Load Balancer keep alive timeout to 60 seconds

---

CHANGELOG.md
ecs-deploy/ecs_service.tf
ecs-deploy/variables.tf

- Enable deployment circuit breaker
- Watch this [video](https://www.youtube.com/watch?v=Y2Ez9M7A95Y) to understand what is it
- AWS Docs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-circuit-breaker.html
- The ways the deployment circuit breaker calculates the failure threshold (when it marks the deployment as FAILED)
- See [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-circuit-breaker.html#failure-threshold)
- Preventing an excessive number of failures during a new deployment. 
- This feature will also send an event notification once the deployment is failing, which will allow us to create an alert based on it

ecs-deploy: enable deployment circuit breaker

---

CHANGELOG.md
elasticache/README.md
elasticache/elasticache.tf
elasticache/variables.tf

* create a custom parameter group, if `parameter_group` variable is omitted instead of checking `maxmemory_policy`, since that is more intuitive
* enforce `in-transit-encryption` for better security (requirement of ISO 27001, see https://www.dataguard.co.uk/blog/iso-27001-annex-a.10-cryptography)
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html
--> ⚠️ Enabling in-transit encryption is a *breaking* change, i.e., it requires to re-create the Redis cluster. If you need zero downtime, you must create a new cluster, swap endpoints in the app, then destroy the old one. Data loss will occur, though.
see also: https://aquasecurity.github.io/tfsec/v0.61.3/checks/aws/elasticache/enable-in-transit-encryption/
security (specifically ISO 27001)
--> Tested …

enable in transit encryption for elasticache

---

CHANGELOG.md
iam/iam-for-deploy-bot/main.tf

Add service discovery access to deploybot
We can easily roll out the service discovery to all projects and deploy using deploybot

iam/iam-for-deploy-bot: add service discovery access

---

CHANGELOG.md
stack/app/elasticache.tf
stack/app/variables.tf

Add elasticache major and minor version to stack/app module
To create elasticache using stack/app module. Otherwise it will throw error complaining that the version and parameter group is different

stack/app: add elasticache major and minor version

---

ecs-deploy/task-definitions/sidecar.json
ecs-deploy/task-definitions/web.json

removes the log stream prefix, since AWS already adds the container name as a prefix, i.e. we had the same prefix twice in the log stream 
name.
cleaner set  up

Remove duplicated log stream prefix

---

ecs-deploy/task-definitions/sidecar.json
ecs-deploy/task-definitions/web.json

Reverts dbl-works/terraform#251
```
│ Error: creating ECS Task Definition (***): ClientException: Fargate requires log configuration options to include awslogs-stream-prefix to support log driver awslogs.
│ 
│   with module.ecs_service_***.aws_ecs_task_definition.main,
│   on .terraform/modules/ecs_service_***/ecs-deploy/ecs_task_definition.tf line 1, in resource "aws_ecs_task_definition" "main":
│    1: resource "aws_ecs_task_definition" "main" {
```

Revert "Remove duplicated log stream prefix"

---

CHANGELOG.md
ecs/cloudwatch-event-rule.tf
ecs/variables.tf
stack/app/ecs.tf
stack/app/variables.tf

Add cloudwatch event rule to monitor the container stopped reason
When the container stopped abruptly, the logs will disappear after a while

[Chore] Add cloudwatch event rule to monitor the stopped container

---

github-backup/README.md
github-backup/src/main.rb
github-backup/variables.tf

- Fix response.error in Ruby lambda
- increase default memory to 2 GiB

[Fix] Github Backup

---

CHANGELOG.md
rds/parameter-group.tf
rds/variables.tf
stack/app/rds.tf
stack/app/variables.tf

log_min_duration_statement determine the statement which exceeds x second to be logged.
If we set it to zero, it means that we will log every statement to the logs.
This will be useful for testing and debugging purpose but not good for the performances as writing logs require disk I/O. 
If a large number of queries are being executed, the constant logging can lead to significant I/O operations, competing with the actual database read/write operations, especially if the logs and database data are on the same disk.

rds: add log_min_duration_statement, log_retention_period variables, log_min_error_statement

---

CHANGELOG.md
rds/rds.tf
rds/variables.tf
stack/app/rds.tf
stack/app/variables.tf

**Current:**
> When you create a new DB instance, the default CA is still rds-ca-2019 until January 25, 2024, when it will be changed to rds-ca-rsa2048-g1
The default CA is going to expired in 2024. Refer to [here](https://aws.amazon.com/blogs/aws/rotate-your-ssl-tls-certificates-now-amazon-rds-and-amazon-aurora-expire-in-2024/)
**Expectations:**
- Set ca_cert_identifier to `rds-ca-rsa2048-g1`
https://github.com/dbl-works/terraform/issues/266

rds: add ca_cert_identifier as var

---

rds/variables.tf

Bump PostgreSQL default version from 14 to 16. Works on CircleCI & AWS.
Tested with a few projects using our standard stack ✅

Update PostgreSQL default version from 14 to 16

---

CHANGELOG.md
stack/app/variables.tf

Set rds_engine_version default value to 16

stack/app: set default rds_engine_version to 16

---

CHANGELOG.md
rds/variables.tf
stack/app/variables.tf

- Set nullable to false for engine_version in rds module
- We don't need to manage default value in both module

rds: set nullable to false for engine_version

---

iam/iam-for-deploy-bot/main.tf

Add extra permission to deploybot.
AWS require the explicit permission to tag ecs resources
```
To ensure your IAM principals continue applying tags to newly created ECS resources on or after March 29, 2024, we strongly recommend adding the following statement(s) to your IAM policies:
Allow Tagging during creation for all ECS Resources
Adding the ecs:TagResource Action as described as follows would Allow tagging during ECS resource creation [2].
```

iam/iam-for-deploy-bot: add ecs:TagResource permission to deploybot

---

CHANGELOG.md
slack/ecr-scanner-notifier/main.tf

The scan notifications are cool, but we get way too many from open "undefined" issues. There are no fixes for these available yet for the underlying Linux packages, so we get spammed with these notifications.
http://go/dbl/91

slack/ecr-scanner-notifier: Reduce noise in ecr scanner notifier

---

CHANGELOG.md
slack/chatbot/main.tf

Grant more permissions/rights to chatbot channel role
When user clicks on `List Dashboard`, channel role does not have enough policy to perform the action and grab the metrics.

slack/chatbot: update chatbot policy so user can access dashboard info

---

cloudwatch-snowflake/README.md
cloudwatch-snowflake/fivetran.tf
cloudwatch-snowflake/versions.tf
fivetran/README.md
fivetran/connectors.tf
fivetran/connectors/google_analytics/README.md
fivetran/connectors/google_analytics/fivetran.tf
fivetran/connectors/google_analytics/versions.tf
fivetran/connectors/lambda/README.md
fivetran/connectors/lambda/examples/cloudwatch_lambda/versions.tf
fivetran/connectors/lambda/fivetran.tf
fivetran/connectors/lambda/main.tf
fivetran/connectors/lambda/variables.tf
fivetran/connectors/lambda/versions.tf
fivetran/versions.tf
lambda/variables.tf

Breaking changes of the Fivetran connector for version 0.1 -> 1.0: https://github.com/fivetran/terraform-provider-fivetran/blob/main/CHANGELOG.md#breaking-changes
We need to allow configuring the Lambda that connects to Fivetran to allow adjusting memory & timeout.

Upgrade Fivetran Terraform provider from 0.1 to 1.0, allow configuring Fivetran-Lambda Sync

---

ecs/variables.tf
stack/app/variables.tf

We don't need container insights in most of the apps.
Lower costs

Disable Container Insights by default

---

aws/ecs-deploy/service/ecs_service.tf

setting `failure_threshold` to `2` causes a force-recreated everytime. Removing it will use the default (1).
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_service#failure_threshold
https://github.com/hashicorp/terraform-provider-aws/issues/35559

fix(ecs-service): remove troublesom failure_threshold

---

aws/s3-shared/guest-iam.tf

Allows launching one bucket per environment for the same guest name (e.g. staging & production)

feat(aws/s3-shared): user-name includes environment

---

azure/blob-storage/README.md
azure/blob-storage/main.tf
azure/blob-storage/variables.tf
azure/container-app/main.tf
azure/container-app/variables.tf
azure/container-registry/main.tf
azure/container-registry/variables.tf
azure/database/postgres/main.tf
azure/database/postgres/network.tf
azure/database/postgres/variables.tf
azure/observability/alerts/main.tf
azure/observability/alerts/variables.tf
azure/observability/monitors/main.tf
azure/observability/monitors/variables.tf
azure/virtual-network/main.tf
azure/virtual-network/private-subnet.tf
azure/virtual-network/public-subnet.tf
azure/virtual-network/variables.tf

Allow passing custom names & tags to all Azure modules.
Tags & names always have a default name following the convention of this repo (`${project}-${environment}`).

chore(azure): allow passing custom names and tags to all resources

---

azure/stack/region/main.tf
azure/stack/region/variables.tf

Some service only need to be created once per region

azure/stack/region: new module

---

aws/cloudwatch-snowflake/main.tf
aws/lambda/README.md

bump nodeJS for lambdas from 16 to 20
AWS is retiring the node 16 runtime.

chore: bump nodeJS for lambdas from 16 to 20

---

aws/stack/global/billing-alerts.tf

Metric alarm and sns topic has to be in the same region

aws/stack/global: fix billing alarm region

---

aws/elasticache/variables.tf
aws/multi-stack/app/variables.tf
aws/stack/app/variables.tf

aws_elasticache_parameter_group will only be created if parameter_group_name is null
See [here](https://github.com/dbl-works/terraform/blob/main/aws/elasticache/elasticache.tf#L92)

aws/elasticache: allow parameter_group_name to be null

---

aws/cloudwatch-kinesis/README.md
aws/cloudwatch-kinesis/cloudwatch-subscription-filter.tf
aws/cloudwatch-kinesis/variables.tf

Allow list of cloudwatch log group names to be passed into the module

aws/cloudwatch-kinesis: replace subscription_log_group_name with subscription_log_group_names

---

aws/ecs/alb.tf
aws/ecs/nlb.tf
aws/ecs/outputs.tf
aws/ecs/variables.tf
aws/multi-stack/app/ecs.tf
aws/multi-stack/app/variables.tf
aws/stack/app/ecs.tf
aws/stack/app/outputs.tf
aws/stack/app/variables.tf

- Allow alb subnet to be defined in the ecs module
- Allow alb subnet type to be defined in the stack module
allow the alb to be placed in the private subnet so its endpoint will not be accessible on internet

aws/ecs: allow alb subnet to be defined

---

aws/s3-private/replication.tf

compact cannot be used to remove null value from a list of objects

aws/s3-private: remove compact

---

aws/multi-stack/app/cloudflare.tf
aws/multi-stack/app/variables.tf
aws/stack/app/cloudflare.tf
aws/stack/app/variables.tf
cloudflare/tls.tf
cloudflare/variables.tf

Set minimum tls version to 1.3, and enable hsts setting

cloudflare: improve cloudflare security

---

aws/ecs/execution-role.tf

The ECS execution role could fail if one of the passed args (secrets or KMS keys) are a NULL object. Terraform's `flatten` does not remove NULL entries, and they blow up the policy.

fix(aws/ecs): ensure we don't pass a NULL object to the policy builder

---

aws/elasticache/variables.tf
aws/stack/app/elasticache.tf
aws/stack/app/variables.tf

Allow passing `transit_encryption_mode` through to the `stack` module.
Required to updated Redis when using the stack module.

fix(aws, stack): elasticache_transit_encryption_mode

---

aws/iam/iam-for-deploy-bot/main.tf

We provide lambda module but whenever you decide to use it there's not enough permissions on deploy-bot, let's fix that
Allow access to manage lambdas for deploy-bot

Allow lambda access

---

aws/s3-shared/guest-iam.tf

No actual change. Just move the S3 access policy from a direct attachment into the group for guest accounts.
ISO27001

chore: move S3 policy for guest accounts into group (from inline)

---

aws/ecs-deploy/service/ecs_service.tf

if you accidentally delete a service via terraform, it can take several hours for AWS to **actually** delete the service. There is nothing you can do during that period to re-launch a service with the same name.

disallow destroying ecs service via terraform

---

.github/workflows/ci.yml
aws/aurora/README.md
aws/aurora/iam.tf
aws/aurora/main.tf
aws/aurora/outputs.tf
aws/aurora/parameter-groups.tf
aws/aurora/security-group.tf
aws/aurora/subnet-group.tf
aws/aurora/variables.tf
aws/aurora/versions.tf
aws/iam/iam-policy-for-redshift-serverless/taggable-resources/README.md
aws/iam/iam-policy-for-redshift-serverless/taggable-resources/outputs.tf
aws/iam/iam-policy-for-redshift-serverless/taggable-resources/redshift-policy.tf
aws/iam/iam-policy-for-redshift-serverless/taggable-resources/variables.tf
aws/iam/iam-policy-for-redshift-serverless/taggable-resources/versions.tf
aws/nat/README.md
aws/nat/nat.tf
aws/rds/outputs.tf
aws/redshift/serverless/README.md
aws/redshift/serverless/endpoint-access.tf
aws/redshift/serverless/main.tf
aws/redshift/serverless/namespace.tf
aws/redshift/serverless/outputs.tf
aws/redshift/serverless/rds-integration.tf
aws/redshift/serverless/security-groups.tf
aws/redshift/serverless/variables.tf
aws/redshift/serverless/workgroup.tf
aws/stack/app/aurora.tf
aws/stack/app/outputs.tf
aws/stack/app/variables.tf

Spin up Redshift Serverless, connects to RDS as source, grants access to ECS so tasks running in ECS can run analytical queries against Redshift instead of RDS.

feat: AWS Aurora & Redshift Serverless

---

aws/elasticache/README.md
aws/elasticache/elasticache.tf
aws/stack/app/elasticache.tf
aws/stack/app/variables.tf

Turns out in my last PR #377 I forgot to remove `ignore_values` lifecycle for `cluster_mode` block 🙈. This PR fixes it.
Bonus: I noticed we have outdated docs so did a tiny brush up there as well to be up to date.
I've migrated our clustered redis to valkey on production, the migration went successful 👍🏼

Fix cluster mode elasticache ignore values
